server:
  port: 8080

spring:
  application.name: backend

  datasource:
    url: jdbc:postgresql://localhost:5433/opexdb
    username: opex
    password: Qm4p8Vn2zA7Lh3Rk9cT5xY
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Crea/aggiorna le tabelle in automatico (ottimo per lo sviluppo, in prod si usa 'validate')
    show-sql: true     # Mostra le query in console
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/opex

# --- CONFIGURAZIONE KEYCLOAK ADMIN CLIENT ---
keycloak-admin:
  server-url: http://localhost:8081
  realm: master
  client-id: admin-cli
  username: admin
  password: kJWQ9TC4FKUFVNi9p2zw
  target-realm: opex
